apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pinshare-backend-data
  namespace: pinshare
  labels:
    app: pinshare-backend
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
