apiVersion: v1
kind: Service
metadata:
  name: pinshare-backend
  namespace: pinshare
  labels:
    app: pinshare-backend
spec:
  type: ClusterIP
  selector:
    app: pinshare-backend
  ports:
    - name: api
      port: 9090
      targetPort: 9090
      protocol: TCP
    - name: libp2p
      port: 50001
      targetPort: 50001
      protocol: TCP
