apiVersion: ENC[AES256_GCM,data:i0c=,iv:djy2PkzT2OhPE2KPIPiAxxTNfSjvyQ1Tc7aaD2UQ52U=,tag:5F8eeolXF7DKT1VFJ3R3kw==,type:str]
kind: ENC[AES256_GCM,data:BWBZoY/E,iv:I807iimbMZMZ1YNGrTs7SPNxGBQ5V5iR34as+7GIQ5I=,tag:VXeV4fc8Jq/ygTTpdzEaBg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:OP4MQ0K0Bo7loFH+9zgOA59fBW/BPeI=,iv:htLMNuRWAklVfPJ07kMe0vkOyF7rCAqB0tRkCBEN1qQ=,tag:BjLpl5GCZIWfAY2oVnuuKg==,type:str]
    namespace: ENC[AES256_GCM,data:jDnfXajwVg0=,iv:dHt57qwz6J04xF0I30oa0G6dOPFSUtbUQoVQKrPMvQw=,tag:C+YLr10jsAidh+cBfFulpw==,type:str]
type: ENC[AES256_GCM,data:jDHjDBki,iv:CJX4iAQJW8tumvJz4FCF9XxUqVUiM/SIo3mKuv1B4as=,tag:oJpQVxSq3C73Fd//7rZEcQ==,type:str]
stringData:
    VT_TOKEN: ""
    GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:DOpITs74gDavE602a7pghZc1+BfBSoxys3zr5ahrN8kN3yCFcvHB5sUJTAklR7EE95nQCNd9nEWTlYdeDNZt6EYtvx+6hzApAA==,iv:mLfjvwJl1PvykM3zZcfe8ID+RG3PO7Ttimx3zvYG118=,tag:u7webQjJPaEMxqP2M8PNeg==,type:str]
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:Mi8EeamDiY1xwKd8qu3w5fiqHso4So21nnpsmAD6APKES5U=,iv:kW4uuEnf4P84byIeTGUu+5jAqzc6WFACrj1bCGhoqf0=,tag:8sGcg6aYlYV69h//0oGEiw==,type:str]
    GOOGLE_REDIRECT_URL: ENC[AES256_GCM,data:lzognJDQ1FE7fD34xruVR1yP6n/fAHS9wa+034qPMGJWK/p16r6SFACOEqdAUqI=,iv:Ts0Wnyksxkyi2sfNKLh91L7ybYWFGDOMyEcXSRsr0aw=,tag:CUJTu5JZS8vsC3pbTyBytA==,type:str]
    PS_ENCRYPTION_KEY: ENC[AES256_GCM,data:GoXqKCHrzwLBxRYpvF9P7AT7tXxIlu74Ryow6q62l2g=,iv:aKE0J8zQ4BHlLjjkiDr98gl/GqzUHk87SGFipwlafGo=,tag:OaRIsuIxuuUW6xlt4JOcPQ==,type:str]
sops:
    age:
        - recipient: age140ptrsjpzlv232gavz0p5clen227nj3fq4fa8d9tgu43pjqamaxqqev5a7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBODd2UlNUMnBFSkVNaE5E
            MHBLUlNMY0ZBTitQVWpYZjV5VlJoYmRJYTM4CkM4RjRhbHBqS0g3OTBXM0RiNDl4
            aVZvSk5sN2JqUGNZSTE4Y1ArRGtxbXcKLS0tIHlIZitBbkVNMTNBQ1d0dWZoQ0oz
            WDhzc0VNalpNdzdKSWdaU0NOM1VucHcK+GH8wdY/78tnir6MErRDMDMs/D7y9UO6
            ZG71Qvr6Z0bQqwe216uyQqdQRi7HG5eIHI2azOCsQzEG6Dsb3eO+0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-14T18:53:47Z"
    mac: ENC[AES256_GCM,data:CK/L7qT/vwGT0i7MJKMjZfV3GFVunU235DGp006mcYPdQDOZqJTc3YvYnMRV2awuU5VKfLU4lF502zJIcqN3qArWmUXeHHOudWifEBspuA33eCIx9659OYFSmtRyLvqzQ7OECG14yUs1LnD9uN8RphLhyYhiY/tt+yjE9Ha08rQ=,iv:13QA2iQv0BQQXgvl/GIZsMMcoYBwtoxQGxQ0oyi0+Tk=,tag:tNXIWn0awFRVuICDHQvX0Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
