// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// BaseMetadata Holds all metadata for a single file, representing the state in the CRDT store.
type BaseMetadata struct {
	// AddedAt Timestamp when the record was first added to the store.
	AddedAt *time.Time `json:"addedAt,omitempty"`

	// FileName LWW-Register for the original file name.
	FileName *string `json:"fileName,omitempty"`

	// FileSHA256 Primary key for the metadata, the SHA256 hash of the file content.
	FileSHA256 string `json:"fileSHA256"`

	// FileType The MIME type of the file.
	FileType string `json:"fileType"`

	// IpfsCID The IPFS Content Identifier (CID) for the file.
	IpfsCID string `json:"ipfsCID"`

	// LastUpdated Timestamp for the last update to this record (LWW clock).
	LastUpdated *time.Time `json:"lastUpdated,omitempty"`

	// ModerationVotes A PN-Counter for community votes to remove the file.
	ModerationVotes *int `json:"moderationVotes,omitempty"`

	// Tags An OR-Set of tags. Keys are the tags, value is always true.
	Tags *map[string]bool `json:"tags,omitempty"`
}

// Error defines model for Error.
type Error struct {
	// Code An optional application-specific error code.
	Code *int32 `json:"code,omitempty"`

	// Message A human-readable error message.
	Message string `json:"message"`
}

// P2PStatus Information about the local P2P node.
type P2PStatus struct {
	// Addresses The listening multiaddresses of the local node.
	Addresses []string `json:"addresses"`

	// ConnectedPeers The number of currently connected peers.
	ConnectedPeers int `json:"connectedPeers"`

	// Id The Peer ID of the local node.
	Id string `json:"id"`
}

// WritableMetadata The set of fields that can be written by a client when adding or updating a file's metadata.
type WritableMetadata struct {
	// FileName LWW-Register for the original file name.
	FileName *string `json:"fileName,omitempty"`

	// FileType The MIME type of the file.
	FileType string `json:"fileType"`

	// IpfsCID The IPFS Content Identifier (CID) for the file.
	IpfsCID string `json:"ipfsCID"`
}

// AddTagJSONBody defines parameters for AddTag.
type AddTagJSONBody struct {
	// Tag The tag to add.
	Tag string `json:"tag"`
}

// ConnectToPeerJSONBody defines parameters for ConnectToPeer.
type ConnectToPeerJSONBody struct {
	// Multiaddr The full multiaddress of the peer (e.g., /ip4/127.0.0.1/tcp/4001/p2p/12D3Koo...).
	Multiaddr string `json:"multiaddr"`
}

// SendDirectMessageJSONBody defines parameters for SendDirectMessage.
type SendDirectMessageJSONBody struct {
	// Message The text message to send.
	Message string `json:"message"`
}

// AddOrUpdateFileJSONRequestBody defines body for AddOrUpdateFile for application/json ContentType.
type AddOrUpdateFileJSONRequestBody = WritableMetadata

// AddTagJSONRequestBody defines body for AddTag for application/json ContentType.
type AddTagJSONRequestBody AddTagJSONBody

// ConnectToPeerJSONRequestBody defines body for ConnectToPeer for application/json ContentType.
type ConnectToPeerJSONRequestBody ConnectToPeerJSONBody

// SendDirectMessageJSONRequestBody defines body for SendDirectMessage for application/json ContentType.
type SendDirectMessageJSONRequestBody SendDirectMessageJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List all file metadata
	// (GET /files)
	ListAllFiles(ctx echo.Context) error
	// Get file metadata by SHA256
	// (GET /files/{fileSHA256})
	GetFileBySHA256(ctx echo.Context, fileSHA256 string) error
	// Add or update file metadata (Upsert)
	// (PUT /files/{fileSHA256})
	AddOrUpdateFile(ctx echo.Context, fileSHA256 string) error
	// Add a tag to a file
	// (POST /files/{fileSHA256}/tags)
	AddTag(ctx echo.Context, fileSHA256 string) error
	// Remove a tag from a file
	// (DELETE /files/{fileSHA256}/tags/{tagName})
	RemoveTag(ctx echo.Context, fileSHA256 string, tagName string) error
	// Vote for file removal
	// (POST /files/{fileSHA256}/votes/removal)
	VoteForRemoval(ctx echo.Context, fileSHA256 string) error
	// List connected peers
	// (GET /p2p/peers)
	ListP2PPeers(ctx echo.Context) error
	// Connect to a peer
	// (POST /p2p/peers)
	ConnectToPeer(ctx echo.Context) error
	// Send a direct message to a peer
	// (POST /p2p/peers/{peerID}/message)
	SendDirectMessage(ctx echo.Context, peerID string) error
	// Get P2P node status
	// (GET /p2p/status)
	GetP2PStatus(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// ListAllFiles converts echo context to params.
func (w *ServerInterfaceWrapper) ListAllFiles(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListAllFiles(ctx)
	return err
}

// GetFileBySHA256 converts echo context to params.
func (w *ServerInterfaceWrapper) GetFileBySHA256(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "fileSHA256" -------------
	var fileSHA256 string

	err = runtime.BindStyledParameterWithOptions("simple", "fileSHA256", ctx.Param("fileSHA256"), &fileSHA256, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter fileSHA256: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetFileBySHA256(ctx, fileSHA256)
	return err
}

// AddOrUpdateFile converts echo context to params.
func (w *ServerInterfaceWrapper) AddOrUpdateFile(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "fileSHA256" -------------
	var fileSHA256 string

	err = runtime.BindStyledParameterWithOptions("simple", "fileSHA256", ctx.Param("fileSHA256"), &fileSHA256, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter fileSHA256: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.AddOrUpdateFile(ctx, fileSHA256)
	return err
}

// AddTag converts echo context to params.
func (w *ServerInterfaceWrapper) AddTag(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "fileSHA256" -------------
	var fileSHA256 string

	err = runtime.BindStyledParameterWithOptions("simple", "fileSHA256", ctx.Param("fileSHA256"), &fileSHA256, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter fileSHA256: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.AddTag(ctx, fileSHA256)
	return err
}

// RemoveTag converts echo context to params.
func (w *ServerInterfaceWrapper) RemoveTag(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "fileSHA256" -------------
	var fileSHA256 string

	err = runtime.BindStyledParameterWithOptions("simple", "fileSHA256", ctx.Param("fileSHA256"), &fileSHA256, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter fileSHA256: %s", err))
	}

	// ------------- Path parameter "tagName" -------------
	var tagName string

	err = runtime.BindStyledParameterWithOptions("simple", "tagName", ctx.Param("tagName"), &tagName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter tagName: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RemoveTag(ctx, fileSHA256, tagName)
	return err
}

// VoteForRemoval converts echo context to params.
func (w *ServerInterfaceWrapper) VoteForRemoval(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "fileSHA256" -------------
	var fileSHA256 string

	err = runtime.BindStyledParameterWithOptions("simple", "fileSHA256", ctx.Param("fileSHA256"), &fileSHA256, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter fileSHA256: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.VoteForRemoval(ctx, fileSHA256)
	return err
}

// ListP2PPeers converts echo context to params.
func (w *ServerInterfaceWrapper) ListP2PPeers(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListP2PPeers(ctx)
	return err
}

// ConnectToPeer converts echo context to params.
func (w *ServerInterfaceWrapper) ConnectToPeer(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ConnectToPeer(ctx)
	return err
}

// SendDirectMessage converts echo context to params.
func (w *ServerInterfaceWrapper) SendDirectMessage(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "peerID" -------------
	var peerID string

	err = runtime.BindStyledParameterWithOptions("simple", "peerID", ctx.Param("peerID"), &peerID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter peerID: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SendDirectMessage(ctx, peerID)
	return err
}

// GetP2PStatus converts echo context to params.
func (w *ServerInterfaceWrapper) GetP2PStatus(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetP2PStatus(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/files", wrapper.ListAllFiles)
	router.GET(baseURL+"/files/:fileSHA256", wrapper.GetFileBySHA256)
	router.PUT(baseURL+"/files/:fileSHA256", wrapper.AddOrUpdateFile)
	router.POST(baseURL+"/files/:fileSHA256/tags", wrapper.AddTag)
	router.DELETE(baseURL+"/files/:fileSHA256/tags/:tagName", wrapper.RemoveTag)
	router.POST(baseURL+"/files/:fileSHA256/votes/removal", wrapper.VoteForRemoval)
	router.GET(baseURL+"/p2p/peers", wrapper.ListP2PPeers)
	router.POST(baseURL+"/p2p/peers", wrapper.ConnectToPeer)
	router.POST(baseURL+"/p2p/peers/:peerID/message", wrapper.SendDirectMessage)
	router.GET(baseURL+"/p2p/status", wrapper.GetP2PStatus)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+Raa2/bOtL+K3z1LtAW8FW248T7Kc3l1HvS1khymsVpA4SWxjJPJFIlKadu4P++GFKS",
	"JUtOfJpsG2A/xXbE4XDmmWcu1L3jiSgWHLhWzujeUd4cImo+vqUK3oOmPtUUv/ugPMlizQR3Rs47EfqK",
	"0DAkUfoMmQlJKFGMByGQGQuhQSTEEhRwzXhA9ByI0lQDYdx8OTo/viRKCwktp+HEUsQgNQOzO/V98A91",
	"deNLFoHSNIrJ3RysHAmekD65o4rMmFSamMVEi3TLdAP4RqM4BGfkuB231+x2mu7eZXcw6nVGnc6fTsOZ",
	"CRlR7Ywcn2poahaB03AkUP8jD5fOSMsEGo5exihCacl44KwaDp70A42gqurZ1VXzHAKmNEhjHVRHSBYw",
	"TkNjIcJptKHbBxpASMYn3b0eOWYSPE1OQvC0ZB4NyUQKP/FQPplJEZGzkw/nrdifOVsUu3h36A72qqpN",
	"JIuoXJJbWOaaZY5smG92JZlTNSdiZn4yGnuCa+C6rHTX9WZ7B96wR/eHBwe9Du3N+sMedPq03+t3oU/3",
	"+r0uDGm/PzjYd/cHA7c3Hbq9A7c/7B747rRofDWnqPKWA12aHyugmAN5P35/QnBNUd2ymjSOQ+ZRXNTe",
	"YjQWz9TR+Lh+i/Hk9IIcWQOQsY+4njGQ5PXR+PhNbsfqvlM6W06BBYvgu/u1H7hh7/tgOQx6391vA28v",
	"6k+HC/eu922wHH53aW/a9wb+Hgxr9Qup0n/ECFD/odjIdMHHSWKet/HAVBYur8+urogXCu/2zZboGF52",
	"MTSeFB2R8EEai38S2oZ2WedDMvnQPBIJz4LEE1GUcKaXZIErUG0JkVhAvXE7+aaMawhA4q6aBhmLMNyH",
	"hpMSu6QrpkKEQDmu2FCKk4/nzQvQBks0UC3yOywVodJqgT81yIKGCRCGNHhHl4qgCUq63TsYn5ltPBH6",
	"zVmizBb40ypXXUz/Ak87qxVa9GvCJHr3czGC18gsxEEZDo2cNK8rghvOiZRCokplnvWEXxNPh5yI2BqO",
	"FIKmqWLw2Ix5BFAawcWtIjQY1z3XqfNIBErRoG4rMk8iypuIJDoNIRWdPt+qxsCGjTLBdWeeuJMLTXVS",
	"A7sxt0ojk9KpSLQNF2FI1p0Qnh6tkpUkKFWHY+SHEKmeY66LklCz/OmMkaz4THQOk89Om8X9dtcdtjqt",
	"Tqvb1l7c7nc63Xbsxu2ue9z7XYirw7dHPpwG79i/bs+iD2Ly9VxdJp/u/r38s+v2+oO94f5Bh771juHU",
	"aaQCD9xWd2+/1W0NnizyuuEwDVExetZBnv5ApaRL/O4JzsHT4E8A5BZb8SSagkTLeImUwHW4JPk6EuPC",
	"kpEGdahifr1w3JeMjx+xu/NDpn0YjiyNwxQmFVvUwfRKMo3Q315t4ZmUZaMZA6y89Jxq4lFOpkDuJNMa",
	"OJkuCSVeyDA7meII6Y8HREibAvAzNQz6SuXZvgryF13Q/G/n/02wVVNCFV+4iPGZqDsSU+RwMiaxFAvm",
	"gyLU80CZlEtNdd6cUgX+usQ3tbQ5KG6oskJ+wvjFHHOjWioNUesLH2vsDcSdsildgkEfNgRaMliYz5T7",
	"a1wa8OSY/MIN4o00kiCDUnJGlW5iqEDzinFl6pc3RGlJNQS2ilUMDZ6FCMpXLEpCqkF94ULPQdqeAy2k",
	"SMhuIU3zVk3M6mbVuiKx/zCFiElFTBuH5gfOQpZcGMscTsZOw1mAtEne6SKhI6xEDJzGzBk5vVan1cOY",
	"o3puwq1tTImfAqjpd86txYwJML8gurHtKhmMAMenVIFLU9fk3Q9GuEH+2MdIZkofhuGp2RpBpWLB07zm",
	"djq2MjA4N2mvEDd/KVQr6xTxU54X/iFh5oyc/2+ve8p22lC2S91kJWWsqhVYftjyQS2qVcvEgkoi7GLS",
	"81TN4mSV4Gcn3/saF1qbt+/XBdZqBwegPfFoIWh4sO1lGTX4yMlMq2I3VXXGb6DREW+Xea33JH/s7oaq",
	"2S8SwwCzJAyXWbCCvxGd6L9+p/9sStnStEabU5NRhCYzkXB/0+e/gd4Ax3RJchPWOB6DTtIItClKPtcx",
	"/Jaut0EUyIXJn8r4M+HsK9b+eQ5ArzKUgnHtNBxuEmi5gl9Tt20I1tb5uZ306rrhxEkN1A99pE3C4a6G",
	"XpZ5HYFcxAl8Y8pQt+DQIiaX5LDGpoj5EMXCzAosnd+sjXGT0RNaCx9OMM1QG2LxejbR+sIvQC5ANiPK",
	"aWCQaLjdcPdNofu5McR9k3ZAN6ZTw4qJJlpgme/RMERxpyLNASVBCJabhm2PJ39cFg4iIQ6plwY/OtvK",
	"bREUFFOpGQ1zq2CHbTrDRNk+8aZtJBPgfiwY16oa/Ie+/1HaQyDcU5iA0m+Fv3y2EKuUmDXRdlmYAZkS",
	"wPfXLq9UN2Uwr34hZ+U5WBXJy6rtG7JyO91frI2pgFJt+s9om63UOeYLGjKfMB4nepM5D8ueLYX66z9i",
	"BVK/+Tu5s53NW2KhttOKpoGtLDc7EEseeamG5JJOX15R33+1jkZ8EraxzD+zdqfITbjnnCrCBYHZDDxd",
	"G4CXNHB+PDk8jfp3YusfpYRyY6dpUN/XZJ7x/XLfojxm85vXlKCASm/+aE+Cm9Q3IY8xRr9GORqkw/xi",
	"NL2UAgTDaAPWhai5xL8PRkz7XtMAO+2VPTnWlXX1ZyRs+Y87mSb5b4WQHZ4Wo6gSAnaLlx0FjQeAa4+4",
	"RYPUxjvWX7tB/npX8FrNXiZ8rderuNoZw6Ytbpsj0nA7/Y+5JyFCje01U34jYPpq4qWzfy3ILKTZhMrU",
	"G6noKrqLdwavWCb/QYx/EhpOhTxPtX3hdP8Ytj4Zy1GlXySyjHbZlCjzYrGgyCGQgit243aczYp3HoPE",
	"dsprZzTY/D84Sa4OQCbuxA5ln2sAUp0sv/PZUdB3D+66i8GJq3qzfjCY7/01vN0PD6IO7wo37n3ty4Ha",
	"08O6ceTuY5LMGLWTkQ1zFFwxcSe2M66v3LSGKNams0ll2FyHLaLZMVHp1T6TBDFYuvmomv3ICrkUaHjn",
	"uQqbfM/68qaiVxbO5gSvoRW0GmSHK5hWq7VxVbpxzdLt1N+zPA0Fmxde+WHry6yapm7b0Ute3aWpc6sG",
	"Tj1q7tEsWgjjTLNf0+6UjpqOtSv0dFREcmyBWI6HEie17/HP+HjVLlxiZvFShvcFcN/ecbxPH90hz2xc",
	"VknwWMzSVyxqEo1VZudx0rMg8NlakK3XwKaag286u/hF5yjgGw3JOwhDkdYq6UAfzfF/T7gl3jYHqWjx",
	"A7GRggBF1CbqnxgYOcjyq3ViS5GfVzMYFfKaATXBL3lqMooMfoZNTikL7fth6Nv1qwZllsBYJpT49sqy",
	"AIhHOEPlbxzscJ2wvpl+pTIfNQrvEeQ3yfa6zFuTrd2m9jJh/drDf3Eqt96kztXpGxS5ltXJ/cYjVXPi",
	"CjP7rePNM2M3HxYQijgy4WWedRpOIkNn5My1jkfttrHvXCg92u/sd9o0Zu1F10E+S3fbFPwxM6YigmcD",
	"3/KEzL4/ZUyfUnLhYusBeVilmjF2OpgyO6Tdzmvbrb8pCDW916MC129LFfqq1+v2qCixUHY/KpfhYuqZ",
	"Idod03OLVjaN3Zhw0HdC3hYko8tW16v/BAAA//9WDQUVTioAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
