apiVersion: v1
kind: Service
metadata:
  name: pinshare-ui
  namespace: pinshare
  labels:
    app: pinshare-ui
spec:
  type: ClusterIP
  selector:
    app: pinshare-ui
  ports:
    - name: http
      port: 5174
      targetPort: 5174
      protocol: TCP
