apiVersion: v1
kind: PersistentVolume
metadata:
  name: ipfs-data-ipfs-0-pv
  labels:
    type: local
    app: ipfs
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/ipfs-data"
    type: DirectoryOrCreate
