apiVersion: v1
kind: Service
metadata:
  name: oauth-broker
  namespace: pinshare
  labels:
    app: oauth-broker
spec:
  type: ClusterIP
  selector:
    app: oauth-broker
  ports:
    - name: http
      port: 8888
      targetPort: 8888
      protocol: TCP
