apiVersion: ENC[AES256_GCM,data:+bY=,iv:0kQtQheasPFw4fcvkGGtqqw5f5+hwm7gENOsO5HYV4M=,tag:VvGw5m4na9/PN8FSrCcnkQ==,type:str]
kind: ENC[AES256_GCM,data:MiAcg6Pf,iv:lWLVPhfCjIZAuo+zcyyjPKwQVXwzEmh7DPsokNdankw=,tag:toWtC3fYsqN0YtIhbFI9aQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:EZiNBV64iaLv+dBAlBHRMCKf+Q==,iv:e2Gz79LYxGBp/77NJ95Q9VeNLFvwZvg3MJvFjlgBkpc=,tag:9+KTH1jqQDEY6H/2EnQwag==,type:str]
    namespace: ENC[AES256_GCM,data:bTFxXejsYx0=,iv:PLrhonUl6ASA9MB5AoU2N1SBj8YKGBu2mjiB4SKAZyI=,tag:GOfU4ToA5VSkyoJJdsnu/w==,type:str]
type: ENC[AES256_GCM,data:6GydhwhW,iv:bz2zi+jflui5XDAhwx8h5Fg0Zcpj0DHIL2TBTBBCogc=,tag:mkQBt9d2Fhzk9Uh0FHgFLw==,type:str]
stringData:
    GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:w2FaQpHJboOwjHo1ewC4NI/JMPuCf2rBcjO9uS/1pQ7MPElqvO5mf1WkeFRT8HTHB/EA82JAcegknokjqnBm9ehU7TgPG9aZWw==,iv:U9xRpHZiPbA6FierXbGozGtWXJZ4AltGJ4bQXuE/3cg=,tag:DSSmiy/Kd5cFIOXTFSes/Q==,type:str]
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:FNn7hKZYUeaqNqbLNgQ/G4eVjlaSLarG4w1Xq/835cv7Wcw=,iv:ogBAsrK11OpeaHDG5P7SIZFeaMS+9SuAvhlq+TkLivM=,tag:IDMC2DZeGYg7CN1S0Ikz4w==,type:str]
    REDIRECT_URL: ENC[AES256_GCM,data:KFxwoL3W3jrN9BBc1kcOi9t182ici9BzbciiTMxTIZT113UM4mmjr5nr,iv:PXSiw8C4z6bOTp1h30qlsKiXQ8Nyn1rvcP+mFZyPq8I=,tag:5qVkFH2ON0187q1UGu8skg==,type:str]
    PORT: ENC[AES256_GCM,data:zCQINw==,iv:r0OPHTGKnfYjrzD8PUjDIsFMHOsKQVlmYDpgQhmTT8g=,tag:QW/1xdnfkb9zCb7H31PBQQ==,type:str]
sops:
    age:
        - recipient: age140ptrsjpzlv232gavz0p5clen227nj3fq4fa8d9tgu43pjqamaxqqev5a7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwanl4THpiTmFiWWRhc2xT
            enJ2YzJ0WHA2UTU3SXVKWStjQW9kNWxKU2d3CjJ5b3kzdkxKbmVuMDB0M1J6eTdZ
            WmVYSHZnKzhuOTFEb01tQkZKUVVXMG8KLS0tIHVDempBYnVNYWllUzdRT3dhZHFs
            MWYwck9qZDNya1hKc1hQM3ZQUFZZUHcKB4zuHGw9iqWFPTGCMTuvIvZn4Lxdu0qo
            2BoNCbGCWoC8pZnsSXcgb0xT4jBf/8PbDAFTvoi4iLKyNw7A5lOzhw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-17T20:12:02Z"
    mac: ENC[AES256_GCM,data:82H5idpsr3hdgZPDzn7LGIMYVGML/kWEliW2Ymr5sJbQABM3DUdfSLvy+jTDqvvdh1eHiA+u+EDVOW1/ITips3bV57Mcr9eReqoplkzRdec2+RtpWVzapMOArVJ3DbfDBRaWBafEhEgY1lUSgvN/j3nPyG0gd4Tsl6jkGCGs3Yw=,iv:xfZ17rWx6bv5H3o4Ld/jLn+qYCgYZ5+2AWHjBVwpXJw=,tag:MtzCPO5Cg1xSpbjDFyBOSw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
