apiVersion: v1
kind: Secret
metadata:
    name: oauth-broker-secret
    namespace: pinshare
type: Opaque
stringData:
    GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:uvzktGJ5DwWZ6q0e6fJUReFo4jNQZouWI23bb9x218HjIEUH+HCHfL55kbXc5OUcmX5kaLFgMOfIPc0H88NMfLQUm8uTsmX+WA==,iv:/8ZZykoskTzqZllns81HZaoTtmU3DLdZ+ksnkuSXlUU=,tag:hNgRXCsF+LGFhhfTMXnTJA==,type:str]
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:hngLddA9CNAOFoYyvBfZC0nDJl9VJ5IVe4lbRiJNRQwoNTU=,iv:85qUChd6zbTGmxlG7laQ27f3HhzLui4tfT6EpQHwX88=,tag:5asZH7LmFtZHJguKxSk9zw==,type:str]
    REDIRECT_URL: ENC[AES256_GCM,data:8F/CmSb4cHUEw7jTFVtnI85Bwrdjx9hgF9+zeL54LDwsHN44J2YZxeBr,iv:QvGa/Cxnmea5P+xXO/TNrxCm6WCCi8cRHL/KzZ6o6Gs=,tag:+0q+pQVNt2Vt9IjyAdqRxA==,type:str]
    PORT: ENC[AES256_GCM,data:oLjQHw==,iv:ULc5A8DjPZLFnTWGgqbHF0SVmebtFQlkBfCvP6T4/ow=,tag:PQsD3qA9BpunpGZCU8MgDQ==,type:str]
sops:
    age:
        - recipient: age140ptrsjpzlv232gavz0p5clen227nj3fq4fa8d9tgu43pjqamaxqqev5a7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFRTdMYmZQM0IveG5adVlx
            KzlYZFB3MVVVNjQrMHhQU3NBb3ZIUExjRFZrCnRTcEoycjZQbnlNQWRVOWh2Vk0r
            TXd0VEx5SS9FT2RIbmFnR2RPM1krd3MKLS0tIFBQaktHdDhoMXBkWmJGT3hKTzJK
            ZzFtQWJCUWp2SUw3NmF0cE1xaFQ0MjAKQzWhvfbpT7m0mnDzOPvTzo5MyDUu7hjM
            Lp+qAFu/AFUE8ibGM0rBz8ZDewGEuP6D+nyOJoEATRlaIjckG6g03Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-17T21:23:00Z"
    mac: ENC[AES256_GCM,data:a/OGHvCGMkzuLpxiiN0lhCHLKZIyyMilZpbJP8qc9jZdQhoxI1bqmWx9fz1w30bgdu8aUGlZEKO98Wo5/1l5fwqH5hiUqIQ4sLb8qhC2ypBpA54XJK1Hocq9SFP+qNomVA4ETIEINrIIFgvSaTaak8Bdw584eKhKQsEq7/W2euc=,iv:w2LUKqc1LqKuHpGyHPoWaRPN/6WRDUiGd/GlqzHGoSk=,tag:za2cnC41Y/Z3qCNjP567Cg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
