apiVersion: v1
kind: Secret
metadata:
    name: pinshare-backend-secret
    namespace: pinshare
type: Opaque
stringData:
    VT_TOKEN: ""
    GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:S1vtsnMz3g9duDzQsvyrcfNKhsnTquwvAjtCtUieHChhB1q4+ViPAX1JN5Cryfi57oPXMMEGDL8gpn198+0JMwmr9BlgpuTUWw==,iv:YOSS5RcbwJCLfRLIzxGcpp3QHNJ6b6gTUgE1RqG9PGE=,tag:wkUrTpT3hBAd0hk48WTr0g==,type:str]
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:OoTEJHv7X4a+84ArXPGNlj4HLDCZPLq+Bviy1A6ymBBtzqo=,iv:4oFOzd/ynJFFAEdiD94bV5S3iHCutGZqXJs+mu6BhCw=,tag:DZKlSPMt3UHtyIdL8iiAAA==,type:str]
    GOOGLE_REDIRECT_URL: ENC[AES256_GCM,data:9KTZk8T+jBoCdqEi1l9gGyUKfw96U6gXEcytFESoWw3GpEiOqryIHfW6pMRWo/TFdyN95ArwKlDh9ovZQbE6,iv:NGMVZJv0QWlWOQxQrasMg1azqJuLH0AO68DbdMtomrs=,tag:Uhns8JZBRLR9X9yRTx/Ljg==,type:str]
    PS_ENCRYPTION_KEY: ENC[AES256_GCM,data:Ej6gu2sf1N2s8ejCB4JLdtms2aghFHMNZCZpGvuD6N4=,iv:XKCDATh9fmtwkfPC1Qg3dfqGPtl28rgXxg0PVs8Mwas=,tag:GgZAYb+Qo9B4KNWet5kZJA==,type:str]
sops:
    age:
        - recipient: age140ptrsjpzlv232gavz0p5clen227nj3fq4fa8d9tgu43pjqamaxqqev5a7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6WXJqREgyTnlwMnl4b1JL
            cFZBZWFCSWVPZ014THdKTWFFeDBUZGsya1U4Cms2b3VYWDhmMzgvbjlOU2s0elJk
            RGlxTVFuZndlOWhjYVZZVm9vdFpnNFkKLS0tIDRSR1ZOU0JySVJzdENBNXJpLy96
            K0ZvOGRZQ1Nwa3Ixd2szRVREOCtzREkKkgvYimkhIJc9GlgNp32dAcX3vpO5gDXj
            NrB9fYMcHUMnsFbDY9FNQxbngMlycbUk8eKBI5jTMmQ4dN6kZxVvMQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-17T21:24:41Z"
    mac: ENC[AES256_GCM,data:eqQL2x5hIZH+9x/0w9kEIuZnTmPKvFauDqiYU6SnU3hcFK7tKTRkmq8iUMTsqhcDcao9kFxKLwNNQKcqTdSMjIpE275LYCAnU/zkEFp/lAfoukQlMpVabfLo4jkbC+dQbSXsICBgYP0l3R1dkFyT0yAfbSiJOK0LVTDBqgYfoWU=,iv:RCWXsuvTgDYtFyHBqezcicuPLUV58b+uPAEhtynC4lo=,tag:vNcCDoiTvDdzWD5QJ/UkfA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
