apiVersion: v1
kind: Secret
metadata:
    name: pinshare-backend-secret
    namespace: pinshare
type: Opaque
stringData:
    VT_TOKEN: ""
    GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:6MGrZ7ozr5KkM4j2k3ryITKLfn6YtdptnTyqkT5b3Bjm/g5IJ7fESo7+lT+1Af3MF5TYVxBKVwlu+VJ9Vc5r+nUB24HUWcnhuA==,iv:Oxwo8wpZ+iojh5ZNuhQok/IOYauyzCd+vCVS5yR9PGY=,tag:w44hSht1eYZocmJgMEltPA==,type:str]
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:rCjRbIRA5DoXfLigwUI0GffH0428yQzZVR4vcrl5an+DqPo=,iv:JweEEUrBNX5z8qnZUDX+k3ZDPBfPm8tshGtiwEDHoEI=,tag:hmh3kOvL697rkIuiKNdgbg==,type:str]
    GOOGLE_REDIRECT_URL: ENC[AES256_GCM,data:KLUKOMvmyJROG6zWAoc3c3sCx7L9RwKdtRH+wCrkRWMKXDRpK17YhtCWtZy5XwIx0y+PAiJDeXZormkNt2QK,iv:U2BDkPQc6prMY9vwZw7WhKk9ngoXNa4KisHgGtSzTms=,tag:uyyfykBV1B9uMFi034mc5g==,type:str]
    PS_ENCRYPTION_KEY: ENC[AES256_GCM,data:sSsQPIR0qYMFfv8SrX2Fqnj0MNXVaSAhkSGm4XxW/28=,iv:y9rcDUGapQmtRjSOVz0KZh9TkKegD4/oIsRGYeH4wBU=,tag:B/BSICePtdJINHRiP/pu/w==,type:str]
    PS_ALLOWED_ORIGINS: ENC[AES256_GCM,data:JWE4kkXWrV0QvBZhJr59Eqzrg5FSRNlq04SlKVRLQb0u8WNG0GqyVmbvPi21ZIz+2dhncQmglrIHt3SQWVhPWakf+T+XaI2qF4p/arL//WPa8sDIt0D1zpoFh2vRh4O0BJEcLI7uKpqnEKjPq/M/bC+l3Lwb+cfGwBY8CIBcZk9VZxnPz5wUh4s=,iv:mIWo7nOmMuJpMFyxF1FWod5i6DFFX6inxPMrvKqODd8=,tag:gvvwaw8MxKI7Mae69KHPBQ==,type:str]
sops:
    age:
        - recipient: age140ptrsjpzlv232gavz0p5clen227nj3fq4fa8d9tgu43pjqamaxqqev5a7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2aThwVSt4WmY4a1A5d3hL
            Zi9Zdm1ncWYzeENUa2xWR0QvMEpZZGYxNGhVCitXOHQyclV1ZUR6YVVjMjFpZXQ2
            UDBycG81TTZmeHFEdlJXbHdNMmkwZEEKLS0tIE9FY3Q1TEMxSFJZRUhVQ1VxR0hU
            UVdXbU9QNTU1L3dydFB3VFVsUGQzcnMKZicTzwckojl5Ea/IVw02riXaWSSl0IK6
            dew/jwUW9iEw7uHxIMmFf9BLRP69DtVNHQXyild/r58TNljF2nlD8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-17T22:10:57Z"
    mac: ENC[AES256_GCM,data:J23s6cRwVhlcBgcULqN13fxUqr0krSXnfr3/h+F42vL1hoGlc+XbVwiotqStnBR49S1O1LkrukRZuz7FEjNrnQqsZTaRovxmhGeHZKpxD6BnirCbP6qbrJnHTSEIPGZc6ETqUmcJO3IclWrkAEQwCeUqlDc/I/ZlhxY52DbV+/Q=,iv:rExJ8p1eiM5MynIHB8OCzxKIMd+RJxcbRk3HItL7ZAM=,tag:udHsUeCAnOizXcUhtirLkA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
